apiVersion: v1
kind: Pod

metadata:
  name: host-test

spec:
  containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]

      volumeMounts:
        - name: host
          mountPath: /host

  volumes:
    - name: host
      hostPath:
        path: /run/desktop/mnt/host/c
        type: Directory