name: Promote to QA

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: true

jobs:
  deploy-qa:
    runs-on: self-hosted
    environment: qa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to QA
        shell: powershell
        run: |
          $image = "aayushkaul/pyspark-learning:${{ inputs.image_tag }}"
          echo "Deploying $image"

  deploy-prod:
    runs-on: self-hosted
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to PROD
        shell: powershell
        run: |
          $image = "aayushkaul/pyspark-learning:${{ inputs.image_tag }}"
          echo "Deploying $image"
          